import styles from "../styles/Home.module.scss";
import { useEffect, useState } from "react";
import { getSession } from "next-auth/react";
import { useRouter } from "next/router";

import Head from "next/head";
import TabButton from "../components/tabButton";
import EventList from "../components/eventList";
import Container from "../components/container";
import Slider from "@/components/slider";

export default function Home({ session }) {
  const [selectedTab, setSelectedTab] = useState("Museec");
  const [categories, setCategories] = useState([]);
  const router = useRouter();

  useEffect(() => {
    fetch("/api/categories")
      .then((res) => res.json())
      .then((categories) => setCategories(categories.data));
  }, []);

  // useEffect(() => {
  //   if (!session) {
  //     router.push("/login");
  //   }
  // }, [session]);

  const handleSelect = (selectedButton) => {
    setSelectedTab(selectedButton);
  };

  return (
    <>
      <Head>
        <title>Moveeda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider />
        <section className={styles.SectionTab}>
          {categories.map((category, key) => (
            <TabButton
              key={category._id}
              onSelect={() => handleSelect(category.name)}
            >
              {category.name.toUpperCase()}
            </TabButton>
          ))}
        </section>
        <EventList selectedTab={selectedTab} />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  };
}
