import styles from "../styles/Home.module.scss";
import { useState } from "react";

import Head from "next/head";
import Header from "@/components/header";
import Hero from "@/components/hero";
import TabButton from "@/components/tabButton";
import MusicEventsList from "@/components/musicEventsList";
import DreenksEventList from "@/components/dreenksEventList";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";

export default function Home() {
  const [selectedTab, setSelectedTab] = useState("Museec");

  const handleSelect = (selectedButton) => {
    setSelectedTab(selectedButton);
  };

  return (
    <>
      <Head>
        <title>Moveeda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <section className={styles.SectionTab}>
          <TabButton onSelect={() => handleSelect("Museec")}>Museec</TabButton>
          <TabButton onSelect={() => handleSelect("Dreenks")}>
            Dreenks
          </TabButton>
          <TabButton onSelect={() => handleSelect("Placees")}>
            Placees
          </TabButton>
        </section>
        {selectedTab === "Museec" && <MusicEventsList />}
        {selectedTab === "Dreenks" && <DreenksEventList />}
        <NavBar />
      </main>
    </>
  );
}
